# Generated by Django 4.1.7 on 2023-05-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_news_options_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
